<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%"><tr valign="middle"><td align="center">
<!-- poner iframe -->
  	<form id="form_imgref" action="" method="post" enctype="multipart/form-data" > 
	<div id="div_mensaje"></div>
	<input id="cod_convenio_imgref" name="cod_convenio_imgref" type="hidden" value="">
	<input type="file" name="lob_upload" ><br><br> 
	<div align="center">
	<input  id="btn_submit_imgref" type="submit" value="Subir Documento"> 
	
	</div>
	</form>
<!--<button id="btn_cancelar_docref">Cancelar</button>-->

	 
</td></tr></table>