<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%"><tr valign="middle"><td align="center">

	<div align="center" class="demo-section" style="font-weight: bold">Mantenimiento de Convenio</div>
	<div align="center" id="div_mensaje"></div>
	<div id="tabs">
	  <ul>
	    <li><a href="#tabs-datosgenerales">DATOS GENERALES</a></li>
	    <li><a href="#tabs-obligaciones">OBLIGACIONES</a></li>
	    <li><a href="#tabs-evaluaciones">EVALUACIONES</a></li>
	    <li><a href="#tabs-estaciones">ESTACIONES</a></li>
	    <li><a href="#tabs-documentos">DOCUMENTOS REFERENTES</a></li>
	  </ul>
	  <div id="tabs-datosgenerales" style="height: 400px">
		<!--	---------------------------------------------------------------------  	-->
	  			<table cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td width="120px">C&oacute;digo Convenio: </td>
						<td width="15px"> </td>
						<td width="480px" id="c_convenio" style="padding-left: 10px"></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td> Nombre de convenio: </td>
						<td> </td>
						<td><input type="text" id="d_convenio" value="" style="width: 100%"></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td>Tipo de convenio: </td>
						<td> </td>
						<td><select id="cbtipoconvenio" style="width: 100%"></select></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
<!--					<tr>-->
<!--						<td>Entidad de convenio: </td>-->
<!--						<td> </td>-->
<!--						<td><select id="cbentidad" style="width: 100%"></select></td>-->
<!--					</tr>-->
<!--					<tr>-->
<!--						<td colspan="3" height="3px"></td>-->
<!--					</tr>-->
<!--					<tr>-->
<!--						<td> Responsable de Entidad: </td>-->
<!--						<td> </td>-->
<!--						<td><input type="text" id="d_responsable_entidad" value="" style="width: 100%"></td>-->
<!--					</tr>-->
<!--					<tr>-->
<!--						<td colspan="3" height="3px"></td>-->
<!--					</tr>-->
					<tr>
						<td> Resoluci&oacute;n de Aprobaci&oacute;n: </td>
						<td> </td>
						<td><input type="text" id="d_resolucion" value="" style="width: 100%"></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td valign="top">Objetivo Espec&iacute;fico: </td>
						<td> </td>
						<td><textarea id="d_objetivo" rows="5" style="width: 100%"></textarea></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					
					<tr>
						<td>Unidad Responsable: </td>
						<td> </td>
						<td><select id="cbunidad" style="width: 100%"></select></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td> Responsable SENAMHI: </td>
						<td> </td>
						<td>
							<select id="cb_responsable_senamhi" style="width: 100%">
								
							</select>
						</td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td> Fecha Inicio / Termino: </td>
						<td> </td>
						<td>
							<input type="text" id="fecha_ini" value="" style="width: 120px">				
							<input type="text" id="fecha_fin" value="" style="width: 120px">
						</td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td colspan="3">
							Entidades:
							<ul style="float: right"><li class="ui-state-default ui-corner-all" style="width: 20px" id="btn_aniadirentidad"><span class="ui-icon ui-icon-plusthick"></span></li></ul>
						</td>
					</tr>
					<tr>
						<td colspan="3">
							<table id="tbl_entconv" border="0" cellpadding="0" cellspacing="0" width="100%"></table>
						</td>
					</tr>
				</table>
	    <!--	---------------------------------------------------------------------  	-->
	  </div>
	  <div id="tabs-obligaciones" style="height: 400px">
	  		<div align="left"><button id="btn_aniadir_obligacion">A&ntilde;adir Obligaci&oacute;n</button></div>
	  		<br>
			<table id="tbl_obligaciones" border="0" cellpadding="0" cellspacing="0" width="660px" class="cl_tbl_obligaciones">
	
			</table>
	  </div>
	  <!--	---------------------------------------------------------------------  	-->
	  
	   <div id="tabs-evaluaciones" style="height: 400px">
	    <table cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td width="140px">Periodo de Evaluaci&oacute;n: </td>
						<td width="15px"> </td>
						<td width="300px"><select id="cb_perioeval" style="width: 100%"></select></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td colspan="3" height="3px" align="center">
							<div id="div_tbl_periodoseval" style="width: 400px">
								
							</div>							
						</td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
		</table>
	  </div>
	  <!--	---------------------------------------------------------------------  	-->
	  <div id="tabs-estaciones" style="height: 400px">
	  		<div align="left"><button id="btn_aniadir_estacion">A&ntilde;adir Estaci&oacute;n</button></div>
	  		<br>
	    	<table id="tbl_estaciones" border="0" cellpadding="0" cellspacing="0" width="660px" class="cl_tbl_estaciones">
	
			</table>
	  </div>
	  <div id="tabs-documentos" style="height: 400px">
	    <div align="left"><button id="btn_aniadir_docref">A&ntilde;adir Documentos Referentes</button></div>
  		<br>
  		<div id="div_tbl_docref">
  			<table id="tbl_docref" border="0" cellpadding="0" cellspacing="0" width="660px">

			</table>
  		</div>    	
	  </div>
	</div>
	
	<br>
	<div align="center">
		<button id="btn_guardar">Guardar</button>
		<button id="btn_cancelar">Salir</button>
	</div>

</td></tr></table>