<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%"><tr valign="top"><td align="center">
	<div align="center" id="div_banner">
		
	</div>
	<div align="center" class="demo-section" style="font-weight: bold">Obligaciones Incumplidas del Convenio</div>
	<div align="center" id="div_mensaje"></div>
	  
	  			<table cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td width="120px">C&oacute;digo Convenio: </td>
						<td width="15px"> </td>
						<td width="720px" id="c_convenio" style="padding-left: 10px"></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td> Nombre de convenio: </td>
						<td> </td>
						<td id="d_convenio"></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td>Tipo de convenio: </td>
						<td> </td>
						<td  id="txt_tipoconvenio">
							
						</td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td> Resoluci&oacute;n de Aprobaci&oacute;n: </td>
						<td> </td>
						<td id="d_resolucion"></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					
					<tr>
						<td>Unidad Responsable: </td>
						<td> </td>
						<td id="d_unidad" ></td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td> Responsable SENAMHI: </td>
						<td> </td>
						<td id="d_responsable_senamhi" >					
						
						</td>
					</tr>
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>
					<tr>
						<td> Fecha Inicio / Termino: </td>
						<td> </td>
						<td>
							<input type="text" id="fecha_ini" value="" style="width: 130px">				
							<input type="text" id="fecha_fin" value="" style="width: 130px">
						</td>
					</tr>
					<tr>
						<td>Periodo: </td>
						<td> </td>
						<td><select id="cbperiodo" style="width: 130px;"></select></td>
					</tr>					
					<tr>
						<td colspan="3" height="3px"></td>
					</tr>					
					<tr>
						<td colspan="3">
							<div id="div_tbl_obligaciones"></div>
							
						</td>
					</tr>
				</table>
	
	<br>
	<div align="center">
		<button id="btn_printt">Imprimir</button>
		<button id="btn_cancelar">Salir</button>
	</div>

</td></tr></table>