<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%"><tr valign="middle"><td align="center">

	<div align="center" class="demo-section" style="font-weight: bold">Mantenimiento de Entidad</div>
	<div align="center" id="div_mensaje"></div>
	<table cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td width="100px">C&oacute;digo: </td>
			<td width="15px"> </td>
			<td width="150px" id="c_entidad" style="padding-left: 10px"></td>
		</tr>
		<tr>
			<td colspan="3" height="5px"></td>
		</tr>
		<tr>
			<td width="100px">Entidad: </td>
			<td width="15px"> </td>
			<td width="150px"><input type="text" id="d_entidad" value="" style="width: 100%"></td>
		</tr>
		<tr>
			<td colspan="3" height="5px"></td>
		</tr>
		<tr>
			<td width="100px">RUC: </td>
			<td width="15px"> </td>
			<td width="150px"><input type="text" id="d_ruc" value="" style="width: 100%" maxlength="11"></td>
		</tr>
		<tr>
			<td colspan="3" height="5px"></td>
		</tr>
		<tr>
			<td width="100px">Sector: </td>
			<td width="15px"> </td>
			<td width="150px"><select id="cbsector" style="width: 100%"></select></td>
		</tr>
	</table>
	<br>
	<div align="center">
		<button id="btn_guardar">Guardar</button>
		<button id="btn_cancelar">Cancelar</button>
	</div>

</td></tr></table>