<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%"><tr valign="middle"><td align="center">

	<div align="center" class="demo-section" style="font-weight: bold">Mantenimiento de Observacion</div>
	<div align="center" id="div_mensaje_eval_observacion"></div><br>
	<table cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td width="80px" valign="top">Observacion: </td>
			<td width="300px"><textarea id="txa_observacioneval" rows="5" style="width: 100%"></textarea></td>
		</tr>
	</table>
	<br>
	<div align="center">
		<button id="btn_guardar_evalobservacion">Guardar</button>
		<button id="btn_cancelar_evalobservacion">Cancelar</button>
	</div>

</td></tr></table>