<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%"><tr valign="middle"><td align="center">

	<div align="center" class="demo-section" style="font-weight: bold">Mantenimiento de Logro</div>
	<div align="center" id="div_mensaje_eval_logro"></div><br>
	<table cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td width="50px" valign="top">Logro: </td>
			<td width="330px"><textarea id="txa_logroeval" rows="5" style="width: 100%"></textarea></td>
		</tr>
	</table>
	<br>
	<div align="center">
		<button id="btn_guardar_evallogro">Guardar</button>
		<button id="btn_cancelar_evallogro">Cancelar</button>
	</div>

</td></tr></table>