<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%"><tr valign="middle"><td align="center">
<input type="hidden" id="codeval" value="">
<table cellpadding="0" cellspacing="0" border="0">
	<tr>
		<th class="ui-state-default" colspan="2">
			<span class="ui-title" id="nroeval"></span><span class="ui-title">&deg; EVALUACION </span> <span class="ui-title" id="tipperioeval"></span>			
		</th>
	</tr>
	<tr>
		<th colspan="2">
			<div id="div_mensaje_eval"></div>			
		</th>
	</tr>
	<tr>
		<td colspan="2" height="8px"></td>
	</tr>
	<tr>
		<td width="170px" class="ui-title">C&oacute;digo:</td>
		<td width="760px" id="c_conv"></td>
	</tr>
	<tr>
		<td colspan="2" height="8px"></td>
	</tr>
	<tr>
		<td class="ui-title">Descripci&oacute;n:</td>
		<td id="d_conv"></td>
	</tr>
	<tr>
		<td colspan="2" height="8px"></td>
	</tr>
	<tr>
		<td class="ui-title">Fecha Inicio /  Termino:</td>
		<td id="f_conv"></td>
	</tr>
	<tr>
		<td colspan="2" height="8px"></td>
	</tr>
	<tr>
		<td class="ui-title">Resoluci&oacute;n:</td>
		<td id="d_resol"></td>
	</tr>
		<tr>
		<td colspan="2" height="3px"></td>
	</tr>
	<tr>
		<td colspan="2"><hr></td>
	</tr>
	<tr>
		<td colspan="2" height="3px"></td>
	</tr>
	<tr>
		<td class="ui-title">Obligaciones:</td>
		<td></td>
	</tr>
	<tr>
		<td colspan="2" height="5px"></td>
	</tr>
	<tr>
		<td colspan="2" id="det_obligaciones"></td>
	</tr>
	<tr>
		<td colspan="2" height="3px"></td>
	</tr>
	<tr>
		<td colspan="2"><hr></td>
	</tr>
	<tr>
		<td colspan="2" height="3px"></td>
	</tr>
	<tr>
		<td class="ui-title">Logros del Periodo:</td>
		<td></td>
	</tr>
	<tr>
		<td colspan="2" height="5px"></td>
	</tr>
	<tr>
		<td colspan="2" id="">
			<div> <button id="btn_aniadir_eval_logro"><span class="ui-icon ui-icon-circle-plus" style="float: left; margin-right: .3em;"></span> A&ntilde;adir Logro</button> </div>
			<table id="tbl_eval_logros" border="1" cellpadding="0" cellspacing="0" width="930px"></table>
		</td>
	</tr>
	<tr>
		<td colspan="2" height="3px"></td>
	</tr>
	<tr>
		<td colspan="2"><hr></td>
	</tr>
	<tr>
		<td colspan="2" height="3px"></td>
	</tr>
	<tr>
		<td class="ui-title">Opiniones del Periodo:</td>
		<td></td>
	</tr>
	<tr>
		<td colspan="2" height="5px"></td>
	</tr>
	<tr>
		<td colspan="2" id="">
			<div> <button id="btn_aniadir_eval_opinion"><span class="ui-icon ui-icon-circle-plus" style="float: left; margin-right: .3em;"></span> A&ntilde;adir Opinion</button> </div>
			<table id="tbl_eval_opinion" border="1" cellpadding="0" cellspacing="0" width="930px"></table>
		</td>
	</tr>
	<tr>
		<td colspan="2" height="3px"></td>
	</tr>
	<tr>
		<td colspan="2"><hr></td>
	</tr>
	<tr>
		<td colspan="2" height="3px"></td>
	</tr>
	<tr>
		<td class="ui-title">Justificaci&oacute;n Gr&aacute;fica:</td>
		<td></td>
	</tr>
	<tr>
	<td colspan="2" height="5px"></td>
	</tr>
	<tr>
		<td colspan="2" >
			<div> <button id="btn_aniadir_eval_img"><span class="ui-icon ui-icon-circle-plus" style="float: left; margin-right: .3em;"></span> A&ntilde;adir Imagen</button> </div>
			<br>
			<div id="div_tbl_imgref">
  			<table id="tbl_imgref" border="0" cellpadding="0" cellspacing="0" width="660px">

			</table>
  		</div> 
  		</td>
	</tr>
	<tr>
		<td colspan="2" height="3px"></td>
	</tr>
	<tr>
		<td colspan="2"><hr></td>
	</tr>
	<tr>
		<td colspan="2" height="3px"></td>
	</tr>
	<tr>
		<td class="ui-title">Observaciones:</td>
		<td></td>
	</tr>
	<tr>
		<td colspan="2" height="5px"></td>
	</tr>
	<tr>
		<td colspan="2" id="">
			<div> <button id="btn_aniadir_eval_observacion"><span class="ui-icon ui-icon-circle-plus" style="float: left; margin-right: .3em;"></span> A&ntilde;adir Observaci&oacute;n</button> </div>
			<table id="tbl_eval_observacion" border="1" cellpadding="0" cellspacing="0" width="930px"></table>
		</td>
	</tr>
</table>
<br>
<div align="center"><button id="btn_guardarevaluacion"> Guardar Evaluci&oacute;n</button></div>
</td></tr></table>