<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%"><tr valign="middle"><td align="center">

	<div align="center" class="demo-section" style="font-weight: bold">Mantenimiento de Obligaci&oacute;n</div>
	<div align="center" id="div_mensaje_obligmant"></div><br>
	<table cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td width="80px" valign="top">Obligaci&oacute;n: </td>
			<td width="15px"> </td>
			<td width="350px"><textarea id="d_obligacion_obligmant" rows="5" style="width: 100%"></textarea></td>
		</tr>
		<tr>
			<td colspan="3" height="5px"></td>
		</tr>
		<tr>
			<td>Responsable: </td>
			<td> </td>
			<td><select id="cbresponsable_obligmant" style="width: 100%"></select></td>
		</tr>
	</table>
	<br>
	<div align="center">
		<button id="btn_guardar_obligmant">Guardar</button>
		<button id="btn_cancelar_obligmant">Cancelar</button>
	</div>

</td></tr></table>