<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%"><tr valign="middle"><td align="center">

	<div align="center">Mantenimiento de Convenio</div>
	<br>
	<div align="center" id="div_mensaje"></div>
	<br>
	<table cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td width="100px">C&oacute;digo: </td>
			<td width="15px"> </td>
			<td width="150px" id="c_tipconv" style="padding-left: 10px"></td>
		</tr>
		<tr>
			<td colspan="3" height="5px"></td>
		</tr>
		<tr>
			<td width="100px">Tipo de Convenio: </td>
			<td width="15px"> </td>
			<td width="150px"><input type="text" id="d_tipconv" value="" style="width: 100%"></td>
		</tr>
	</table>
	<br>
	<div align="center">
		<button id="btn_guardar">Guardar</button>
		<button id="btn_cancelar">Cancelar</button>
	</div>

</td></tr></table>