<div align="center">
	<table width="1050px" border="0" cellpadding="0" cellspacing="0">
		<tr height="20px">
			<td colspan="7"></td>
		</tr>
		<tr height="800px">
			<td width="20px"></td>
			<td width="260px" align="center" valign="top" class="demo-section">
				<div class="ui-state-default ui-corner-all" align="center">Listado de Estaciones</div>
				<div>
				    <ul><li class="ui-state-default ui-corner-left" style="width: 10%;float:left;"><span class="ui-icon ui-icon-search"></span></li></ul>
					<input type="text"  id="buscar_tree" placeholder="Filtro" value="" style="float:left;width:89%">
				</div>
				<div id="tree-div" align="left" style="overflow-y:scroll; height:92%;width:96%;padding:10px"></div>				
			</td>
			<td width="10px"></td>
			<td width="750px" align="center" class="demo-section"><div id="c_mapa" style="width: 750px;height: 800px;margin: 0; padding: 0;"></div></td>		
			<td width="20px"></td>
		</tr>
		<tr height="5px">
			<td colspan="7"></td>
		</tr>
		<!-- 
		<tr >
			<td></td>
			<td align="center" colspan="5">
				 <div class="demo-section" style="width:470px">
				 	<div class="ui-state-default ui-corner-top" align="center">Rango de Fechas</div><br>
	                <label for="fecha_ini">Fecha Inicio:</label>
	                <input id="fecha_ini" value="" readonly="readonly" />
	
	                <label for="fecha_fin" style="margin-left:3em">Fecha Fin:</label>
	                <input id="fecha_fin" value=""  readonly="readonly"/ >
           	 	</div>
			</td>
			<td></td>
		</tr>
		<tr height="5px">
			<td colspan="7"></td>
		</tr>
		 		
		<tr>
			<td></td>
			<td align="center" colspan="5"><button id="btn_generargrafico">Generar Gr&aacute;fico</button></td>
			<td></td>
		</tr>
		<tr height="5px">
			<td colspan="7"></td>
		</tr>
		-->
		<tr height="300px">
			<td></td>
			<td colspan="5" align="left" class="demo-section"><div id="div_grafico" style="height: 450px; width: 87%; position: relative;"></div></td>
			<td></td>
		</tr>
		<tr height="20px">
			<td colspan="7"></td>
		</tr>
	</table>
</div>
