<div align="center">
	<table width="450px" border="1" cellpadding="0" cellspacing="0">
		<tr>
			<td width="120px" class="ui-state-default">Direcci&oacute;n Regional:</td>
			<td id="wi_googlemaps_direc_regional"> dr </td>
		</tr>
		<tr>
			<td class="ui-state-default">Estaci&oacute;n:</td>
			<td id="wi_googlemaps_estacion"> estacion </td>
		</tr>
	</table>
	<br>
	<div style="width: 450px">
		<table width="450px" border="0" cellpadding="0" cellspacing="0"  id="c_table_alertasestacion_googlemaps">		
		</table>
	</div>
</div>
