<div align="center">
	<table width="450px" border="1" cellpadding="0" cellspacing="0">		
		<tr>
			<td class="ui-state-default">Estaci&oacute;n:</td>
			<td id="c_estacion_coment"> estacion </td>
		</tr>
		<tr>
			<td width="120px" class="ui-state-default">Direcci&oacute;n Regional:</td>
			<td id="c_dirreg_coment"> dr </td>
		</tr>
	</table>
</div>


<br>


<div id="tabs">
  <ul>
<!--    <li><a href="#tabs-1">Comentarios de la Estaci&oacute;n</a></li>-->
    <li><a href="#tabs-2">Valores Modificados</a></li>
  </ul>
  
<!--  <div id="tabs-1">-->
<!--  	<div id="div_tabladatosestaciones_comentarios">-->
<!--   	 	<table width="100%" border="1" cellpadding="0" cellspacing="0" id="c_tabladatosestaciones_comentarios"></table>-->
<!--    </div>-->
<!--    <br>-->
<!--    <div align="center"><button id="btn_nuevocomentario">Nuevo Comentario</button></div>-->
<!--  </div>-->
  
  <div id="tabs-2">
 	 <div id="div_tabladatosestaciones_historialvalores">
  		<table width="100%" border="1" cellpadding="0" cellspacing="0" id="c_tabladatosestaciones_historialvalores"></table>
  	</div>
  </div>  
</div>