<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0"><tr><td>
	<table border="0" cellpadding="0" cellspacing="0">
		<tr>
			<td colspan="4" height="10px"></td>
		</tr>
		<tr>
			<td colspan="4"><div id="div_mensaje_editor"></div></td>
		</tr>
		<tr>
			<td colspan="4" height="10px"></td>
		</tr>
		<tr>
			<td width="15px"></td>
			<td width="90px"><b>Estaci&oacute;n:</b></td>
			<td width="220px" id="txtestacion"></td>
			<td width="15px"><input type="hidden" id="codestacion"></td>
		</tr>
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td></td>
			<td valign="top"><b>Dir. Regional:</b></td>
			<td id="txtdirreg"></td>
			<td ></td>
		</tr>
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td ></td>
			<td  valign="top"><b>Criterio:</b></td>
			<td id="txtcriterio"></td>
			<td ><input type="hidden" id="hd_codgrupo"><input type="hidden" id="hd_codparam"><input type="hidden" id="hd_codcriterio"></td>
		</tr>
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td ></td>
			<td  valign="top"><b>Fecha:</b></td>
			<td id="txtfecha"></td>
			<td ></td>
		</tr>
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td ></td>
			<td ><b>Valor Actual:</b></td>
			<td id="txtvaloractual"></td>
			<td ><input type="hidden" id="hd_codvaloractual"></td>
		</tr>
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td></td>
			<td><b>Nuevo Valor:</b></td>
			<td id="td_nuevovalor">
<!--				<input type="text" id="txtnuevovalor" style="width:100%" value="">-->
			</td>
			<td></td>
		</tr> 
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td></td>
			<td><b>Comentario:</b></td>
			<td>
<!--				<textarea id="txacomentario" style="width:100%" ></textarea>-->
				<select id="cb_comentario" " style="width:100%">
					<option value="DATOS POR RPM">1 - DATOS POR RPM</option>
					<option value="ORDENANDO FILAS">2 - ORDENANDO FILAS</option>
					<option value="DATOS DE TELEFONO">3 - DATOS DE TELEFONO</option>
					<option value="CORRECION">4 - CORRECION</option>
				</select>
			</td>
			<td></td>
		</tr> 
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td></td>
			<td colspan="2" align="center"><button id="btn_guardar">Guardar</button><button id="btn_cerrar">Cerrar</button></td>
			<td></td>
		</tr> 
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
	</table>
</td></tr></table>