<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0"><tr><td>
	<table border="0" cellpadding="0" cellspacing="0">
		<tr>
			<td colspan="4" height="10px"></td>
		</tr>
		<tr>
			<td colspan="4"><div id="div_mensaje"></div></td>
		</tr>
		<tr>
			<td colspan="4" height="10px"></td>
		</tr>
		<tr>
			<td width="15px"></td>
			<td width="80px"><b>Estaci&oacute;n:</b></td>
			<td width="150px" id="txtestacion"></td>
			<td width="15px"></td>
		</tr>
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td ></td>
			<td ><b>Criterio:</b></td>
			<td id="txtcriterio"></td>
			<td ></td>
		</tr>
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td ></td>
			<td ><b>Fecha:</b></td>
			<td id="txtfecha"></td>
			<td ></td>
		</tr>
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td ></td>
			<td ><b>Valor Actual:</b></td>
			<td id="txtvaloractual"></td>
			<td ></td>
		</tr>
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td></td>
			<td><b>Nuevo Valor:</b></td>
			<td><input type="text" id="txtnuevovalor" style="width:100%" value=""></td>
			<td></td>
		</tr> 
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td></td>
			<td><b>Comentario:</b></td>
			<td><textarea id="txacomentario" style="width:100%" ></textarea></td>
			<td></td>
		</tr> 
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
		<tr>
			<td></td>
			<td colspan="2" align="center"><button id="btn_guardar">Guardar</button></td>
			<td></td>
		</tr> 
		<tr>
			<td colspan="4" height="8px"></td>
		</tr>
</td></tr></table>