<div id="div_estaciones">
<table width="100%" border="1" cellpadding="0" cellspacing="0" id="c_tabla_estaciones">
	<thead>
		<tr>
			<th colspan="12" class="ui-state-default">Lista de Estaciones</th>
		</tr>
		<tr>
			<th rowspan="2" width="110px">C&oacute;digo Estaci&oacute;n</th>
			<th rowspan="2">Nombre Estaci&oacute;n</th>
			<th rowspan="2">Direcci&oacute;n Regional</th>
			<th colspan="3" class="ui-state-default">Latitud</th>
			<th colspan="3" class="ui-state-default">Longitud</th>			
			<th rowspan="2">Tipo</th>
			<th rowspan="2" width="20px">Editar</th>
			<th rowspan="2" width="20px">Datos<BR>Movil</th>
		</tr>
		<tr>
			<th width="60px">Hora</th>
			<th width="70px">Minutos</th>
			<th width="75px">Segundos</th>
			<th width="50px">Hora</th>
			<th width="70px">Minutos</th>
			<th width="75px">Segundos</th>
		</tr>
	</thead>
</table>
</div>
<!-- 
<br><br>
<div><button id="btn_nuevaestacion">Nueva Estacion</button></div>
 -->
