<table border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td colspan="4" height="20px"></td>
	</tr>
	<tr>
		<td width="15px"></td>
		<td width="120px"><b>C&oacute;odigo:</b></td>
		<td width="240px" id="txtcodestacion"></td>
		<td width="15px"></td>
	</tr>
	<tr>
		<td colspan="4" height="8px"></td>
	</tr>
	<tr>
		<td></td>
		<td><b>Estaci&oacute;n:</b></td>
		<td><input type="text" id="txtestacion" style="width:100%" value=""></td>
		<td></td>
	</tr> 
	<tr>
		<td colspan="4" height="8px"></td>
	</tr>
	<tr>
		<td></td>
		<td><b>Direcci&oacute;n Regional:</b></td>
		<td><select id="cbdirreg" style="width:100%"></select></td>
		<td></td>
	</tr>
	<tr>
		<td colspan="4" height="8px"></td>
	</tr>
	<tr>
		<td></td>
		<td valign="top"><b>Coordenadas:</b></td>
		<td class="ui-corner-all" style="border: 1px solid;">			
			<table border="0" cellpadding="0" cellspacing="0">
				<tr><td colspan="9" height="5px"></td></tr>
				<tr>
					<td width="2px"></td>
					<td width="57px"></td>
					<td width="2px"></td>
					<td width="61px" align="center"><b>Hora</b></td>
					<td width="2px"></td>
					<td width="61px" align="center"><b>Minuto</b></td>
					<td width="2px"></td>
					<td width="61px" align="center"><b>Segundo</b></td>
					<td width="2px"></td>
				</tr>
				<tr>
					<td></td>
					<td><b>Latitud:</b></td>
					<td></td>
					<td><input type="text" id="txtlathora" style="width:55px" value="" class="number"></td>
					<td></td>
					<td><input type="text" id="txtlatmin" style="width:55px" value="" class="number"></td>
					<td></td>
					<td><input type="text" id="txtlatseg" style="width:55px" value="" class="number"></td>
					<td></td>
				</tr>
				<tr><td colspan="9" height="5px"></td></tr>
				<tr>
					<td></td>
					<td><b>Longitud:</b></td>
					<td></td>
					<td><input type="text" id="txtlnghora" style="width:55px" value="" class="number"></td>
					<td></td>
					<td><input type="text" id="txtlngmin" style="width:55px" value="" class="number"></td>
					<td></td>
					<td><input type="text" id="txtlngseg" style="width:55px" value="" class="number"></td>
					<td></td>
				</tr>
				<tr><td colspan="9" height="5px"></td></tr>
				<tr>
					<td></td>
					<td><b>MSNM:</b></td>
					<td></td>
					<td colspan="5"><input type="text" id="txtmsnm" style="width:100%" value="" class="number"></td>
					<td></td>
				</tr>
				<tr><td colspan="9" height="5px"></td></tr>
			</table>
		</td>
		<td></td>
	</tr> 
	<tr>
		<td colspan="4" height="8px"></td>
	</tr>
	<tr>
		<td></td>
		<td><b>Tipo Estaci&oacute;n:</b></td>
		<td><select id="cbtipo" style="width:100%"></select></td>
		<td></td>
	</tr>
	<tr>
		<td colspan="4" height="8px"></td>
	</tr>
	<tr>
		<td></td>
		<td><b>Sub-Tipo Estaci&oacute;n:</b></td>
		<td><select id="cbsubtipo" style="width:100%"></select></td>
		<td></td>
	</tr>
	<tr>
		<td colspan="4" height="8px"></td>
	</tr>
	<tr>
		<td></td>
		<td><b>Categoria Estaci&oacute;n:</b></td>
		<td><select id="cbcategoria" style="width:100%"></select></td>
		<td></td>
	</tr>
	<tr>
		<td colspan="4" height="8px"></td>
	</tr>
	<tr>
		<td></td>
		<td><b>Entidad:</b></td>
		<td><select id="cbentidad" style="width:100%"></select></td>
		<td></td>
	</tr>
	<tr>
		<td colspan="4" height="8px"></td>
	</tr>
	<tr>
		<td></td>
		<td><b>Envio Movil:</b></td>
		<td><select id="cbmovil" style="width:100%"></select></td>
		<td></td>
	</tr>
	<tr>
		<td colspan="4" height="8px"></td>
	</tr>
	<tr>
		<td colspan="4" align="center"><button id="btnguardar">Guardar</button><button id="btncerrar">Cerrar</button></td>
	</tr>
	<tr>
		<td colspan="4" height="20px"></td>
	</tr>
</table>