<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td align="center">

	<table width="600px" border="1" cellpadding="0" cellspacing="0">
		<tr>			
			<td width="120px" class="ui-state-default">Estaci&oacute;n:</td>
			<td id="wi_googlemaps_estacion_det"> est </td>
		</tr>
		<tr>
			<td class="ui-state-default">Direcci&oacute;n Regional:</td>
			<td id="wi_googlemaps_dirreg_det"> dr </td>
		</tr>
		<tr>
			<td class="ui-state-default">Fecha</td>
			<td id="wi_googlemaps_fecha_det">  </td>
		</tr>
		<tr>
			<td class="ui-state-default">Hora Prevista</td>
			<td id="wi_googlemaps_horaprevista_det">  </td>
		</tr>
		<tr>
			<td class="ui-state-default">Hora de LLegada</td>
			<td id="wi_googlemaps_horallegada_det">  </td>
		</tr>		
		</table>
		<br><br>
		<div style="border: 1px solid">
			<table width="598px" border="1" cellpadding="0" cellspacing="0"  id="c_table_monitoreodatosestaciondetalle_googlemaps">		
			</table>
		</div>	
		<br><br>
		<div align="center">
			<button id="btn_cerrar">Cerrar</button>
		</div>
	

</td></tr></table>