<div align="center">
	<table width="540px" border="1" cellpadding="0" cellspacing="0">
		<tr>			
			<td width="120px" class="ui-state-default">Estaci&oacute;n:</td>
			<td id="wi_googlemaps_estacion"> est </td>
		</tr>
		<tr>
			<td class="ui-state-default">Direcci&oacute;n Regional:</td>
			<td id="wi_googlemaps_dirreg"> dr </td>
		</tr>
		<tr>
			<td class="ui-state-default">Tipo Estaci&oacute;n:</td>
			<td id="wi_googlemaps_tipoestacion"> tipo </td>
		</tr>
		<tr>
			<td colspan="2">
				<table border="0" cellpadding="0" cellspacing="0">
					<tr>
						<td width="60px" class="ui-state-default">Latitud:</td>
						<td width="6px"></td>
						<td width="106pxpx" id="wi_googlemaps_lat">x</td>
						<td width="60pxpx" class="ui-state-default">Longitud:</td>
						<td width="6px"></td>
						<td width="106pxpx" id="wi_googlemaps_lng">y</td>
						<td width="50pxpx" class="ui-state-default">MSNM:</td>
						<td width="6px"></td>
						<td width="50pxpx" id="wi_googlemaps_msnm">z</td>
					</tr>
				</table>
			</td>			
		</tr>
		<tr height="8px"><td colspan="2"></td></tr>
		<tr><td colspan="2">
			<table width="540px" border="1" cellpadding="0" cellspacing="0"  id="c_table_monitoreodataestacion_googlemaps">		
			</table>
		</td></tr>
	</table>
</div>
