<div align="center">
	<table width="540px" border="1" cellpadding="0" cellspacing="0">
		<tr>			
			<td width="120px" class="ui-state-default">Estaci&oacute;n:</td>
			<td id="c_estacion"> est </td>
		</tr>
		<tr>
			<td class="ui-state-default">Direcci&oacute;n Regional:</td>
			<td id="c_dirreg"> dr </td>
		</tr>
	</table>
	<br>
	<div align="center"><label for="fecha_ini">Fecha Inicio:</label>
                <input id="fecha_ini" value="" readonly="readonly" />

                <label for="fecha_fin" style="margin-left:3em">Fecha Fin:</label>
                <input id="fecha_fin" value=""  readonly="readonly"/ ></div>
	<br>
	<div  align="center"><button id="btn_buscardatos">Buscar Datos</button></div>
	<br>
	<div id="c_tablarpta" ></div>
</div>
