<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0"><tr><td>
<div id="div_mensaje_editor" align="center">
	<div>
	<div id="div_mensaje_editor_int"></div>
	<table border="0" cellpadding="0" cellspacing="0">
		<tr>
			<td width="130px" style="font-weight: bold">COD ESTACION:</td>
			<td width="250px" id="editor_codestacion"></td>
		</tr>
		<tr><td colspan="2" height="5px"></td></tr>
		<tr>
			<td style="font-weight: bold">ESTACION:</td>
			<td id="editor_estacion"></td>
		</tr>
		<tr><td colspan="2" height="5px"></td></tr>
		<tr>
			<td style="font-weight: bold">FECHA:</td>
			<td id="editor_fecha"></td>
		</tr>
		<tr><td colspan="2" height="5px"></td></tr>
		<tr>
			<td style="font-weight: bold">HORA SINOPTICA:</td>
			<td id="editor_hora_sinop"></td>
		</tr>
		<tr><td colspan="2" height="5px"></td></tr>
		<tr>
			<td style="font-weight: bold">HORA DE REGISTRO:</td>
			<td><select id="cb_editor_horareg" style="width: 100px"></select></td>
		</tr>
	</table>
	</div>
	<br>
	<div id="editor_tbl"></div>
	<br>
	<div align="center"><button id="btn_guardar_editor">Guardar</button><button id="btn_salir_editor">Salir</button></div>
</div>
</td></tr></table>