<div style="background-color: #144f8f;height: 100%" >
	<div align="center" style="padding-top: 20px;padding-bottom: 20px" >
	   <div class="demo-section k-content" align="center" style="width: 900px;font-weight: bold;font-size: 20px" id="txt_emp">
			RETRASO DE LAS ESTACIONES AUTOMATICAS		
		</div>
		<div id="div_leyenda" class="demo-section k-content" align="right" style="width: 1200px;font-weight: bold;font-size: 20px">
			LEYENDA :
		</div>
		<div style="width: 1200px">
	        <div id="div_siap"  class="demo-section k-content" style="width: 48%;float: left;font-size: 20px;">SIAP</div>
	        <div id="divoracle"  class="demo-section k-content" style="width: 48%;float: right;font-size: 20px;" >ORACLE</div>
        </div>
		<div style="width: 1200px">
	        <div id="div_map_siap"  class="" style="width: 48%;float: left;height: 680px"></div>
	        <div id="div_map_oracle"  class="" style="width: 48%;float: right;height: 680px" ></div>
        </div>
		
	</div>
</div>
