<div style="background-color: #144f8f;height: 100%;width: 100%">
	<div class="cent" >
	    <div class="cent_tabl">
	      <div><img src="../../img/bg_caja_sup.png" width="440" height="60"/></div>
	
	      <div class="cont_logi">
	
	      <fieldset>
	          <p>
	
	          <div class="requisito">
	          <label class="label_logeo" for="nombre">Usuario<span class="span_logeo">Ingrese su usuario</span></label>
	          <input class="input_logeo" type="text" name="txtuser" id="txtuser" />
	          <!----><span class="span_logeo" id="usuario-mens" class="mens"></span>
	          </div>
	
	          <div class="requisito">
	          <label class="label_logeo" for="pass">Clave <span class="span_logeo">Ingrese su clave</span></label>
	          <input class="input_logeo" type="password" name="txtpass" id="txtpass"/>
	          <!----><span class="span_logeo" id="password-mens" class="mens"></span>
	          </div>
	
	          <div class="requisito">
	          <label class="label_logeo" for="capcha">Capcha <span class="span_logeo">Ingrese la imagen</span></label>
	          <input class="input_logeo" type="text" name="captcha" id="captcha" class="captcha" style="width:85px;"/>
	          <div class="captcha-container"><img id="img-captcha" src="captcha?size=little" alt="captcha" /><!-- Ojo esta img tiene que medir + de 40px--></div>
	          <!----><span class="span_logeo" id="captcha-mens" class="mens"></span>
	          </div>
	
	          </p>
	
	          <p>
	
	          <div class="requisito">
	            <input type="button" class="ingr" id="btningreso" value="INGRESAR"/>
	          </div>
	
	          </p>
	        </fieldset>
	      </div>
	
	      <div><img src="../../img/bg_caja_inf.png" width="440" height="60"/></div>
	    </div>
	</div>
</div>