<style>
body, html {
    height: 100%;
    background-repeat: no-repeat;
    background-image: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));
}

.card-container.card {
	width: 350px;
    max-width: 550px;
    padding: 40px 40px;
    
}

.btn {
    font-weight: 700;
    height: 36px;
    -moz-user-select: none;
    -webkit-user-select: none;
    user-select: none;
    cursor: default;
}

/*
 * Card component
 */
.card {
    background-color: #F7F7F7;
    /* just in case there no content*/
    padding: 20px 25px 30px;
    margin: 0 auto 25px;
    margin-top: 50px;
    /* shadows and rounded borders */
    -moz-border-radius: 2px;
    -webkit-border-radius: 2px;
    border-radius: 2px;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}

.profile-img-card {
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}

/*
 * Form styles
 */
.profile-name-card {
    font-size: 16px;
    font-weight: bold;
    text-align: center;
    margin: 10px 0 0;
    min-height: 1em;
}

.reauth-email {
    display: block;
    color: #404040;
    line-height: 2;
    margin-bottom: 10px;
    font-size: 14px;
    text-align: center;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin #inputEmail,
.form-signin #inputPassword {
    direction: ltr;
    height: 44px;
    font-size: 16px;
}

.form-signin input[type=email],
.form-signin input[type=password],
.form-signin input[type=text],
.form-signin button {
    width: 100%;
    display: block;
    margin-bottom: 10px;
    z-index: 1;
    position: relative;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin .form-control:focus {
    border-color: rgb(104, 145, 162);
    outline: 0;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
}

.btn.btn-signin {
    /*background-color: #4d90fe; */
    background-color: rgb(104, 145, 162);
    /* background-color: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));*/
    padding: 0px;
    font-weight: 700;
    font-size: 14px;
    height: 36px;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    border: none;
    -o-transition: all 0.218s;
    -moz-transition: all 0.218s;
    -webkit-transition: all 0.218s;
    transition: all 0.218s;
}

.btn.btn-signin:hover,
.btn.btn-signin:active,
.btn.btn-signin:focus {
    background-color: rgb(12, 97, 33);
}

.forgot-password {
    color: rgb(104, 145, 162);
}

.forgot-password:hover,
.forgot-password:active,
.forgot-password:focus{
    color: rgb(12, 97, 33);
}

</style>
<div style="height: 100vh">
        <div class="flex-center flex-column">
			<div class="card card-container">
		            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
		            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
		            <p id="profile-name" class="profile-name-card"></p>
		           
		                <span id="reauth-user" class="reauth-user"></span>
		                <input type="text" id="txtuser" class="form-control" placeholder="Usuario" required autofocus>
		                <input type="password" id="txtpass" class="form-control" placeholder="Contraseña" required>
		                <div id="remember" class="checkbox">
		                    <label>
		                        <input type="checkbox" value="remember-me">Recordar
		                    </label>
		                </div>
		                <button class="btn btn-lg btn-primary btn-block btn-signin" id="btningreso">Ingresar</button>
		            
		            <a href="#" class="forgot-password">
		                Solicitar contraseña
		            </a>
		        </div><!-- /card-container -->
			</div>
</div>
<!--
<div style="background-color: #144f8f;height: 100%;width: 100%">
	<div class="cent" >
	    <div class="cent_tabl">
	      <div><img src="../../img/bg_caja_sup.png" width="440" height="60"/></div>
	
	      <div class="cont_logi">
	
	      <fieldset>
	          <p>
	
	          <div class="requisito">
	          <label class="label_logeo" for="nombre">Usuario<span class="span_logeo">Ingrese su usuario</span></label>
	          <input class="input_logeo" type="text" name="txtuser" id="txtuser" />
	          <span class="span_logeo" id="usuario-mens" class="mens"></span>
	          </div>
	
	          <div class="requisito">
	          <label class="label_logeo" for="pass">Clave <span class="span_logeo">Ingrese su clave</span></label>
	          <input class="input_logeo" type="password" name="txtpass" id="txtpass"/>
	          <span class="span_logeo" id="password-mens" class="mens"></span>
	          </div>
	
	          <div class="requisito">
	          <label class="label_logeo" for="capcha">Capcha <span class="span_logeo">Ingrese la imagen</span></label>
	          <input class="input_logeo" type="text" name="captcha" id="captcha" class="captcha" style="width:85px;"/>
	          <div class="captcha-container"><img id="img-captcha" src="captcha?size=little" alt="captcha" />
	          <span class="span_logeo" id="captcha-mens" class="mens"></span>
	          </div>
	
	          </p>
	
	          <p>
	
	          <div class="requisito">
	            <input type="button" class="ingr" id="btningreso" value="INGRESAR"/>
	          </div>
	
	          </p>
	        </fieldset>
	      </div>
	
	      <div><img src="../../img/bg_caja_inf.png" width="440" height="60"/></div>
	    </div>
	</div>
</div>

  -->