<html>
	<head>
		<?php		
		echo $this->headMeta() . "\n";
		echo $this->headTitle() . "\n";
	
		?>
		<style type="text/css">
			.printable {
				border: 1px dotted #CCCCCC ;
				padding: 10px 10px 10px 10px ;
			}
		</style>

		
		<?php echo $this->util()->getStyle(); ?>
		<link href="<?php echo $this->util()->getPath(); ?>theme/blue_explora/jquery-ui.css" rel="stylesheet" type="text/css" id="jquery_theme_link" />
		<link href="<?php echo $this->util()->getImage("refbar.ico"); ?>" rel="shortcut icon" type="image/x-icon" />
		<link href="<?php echo $this->util()->getImage("refbar.ico"); ?>" rel="icon" type="image/x-icon" />
		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;language=es"></script>
		<?php
			echo $this->util()->getScript("js/common");			
			echo $this->util()->getScript("js/jqplot");
			
			$controller = $this->util()->getScriptJSController();
			$controllerAction = $this->util()->getScriptJSControllerAction();
			$leave = $this->util()->getScriptLeave();
			
			if(strlen($controller) > 0) {
				echo $controller;
			}
			
			if(strlen($controllerAction) > 0) {
				echo $controllerAction;
			}
			
			if(strlen($leave) > 0) {
				echo $leave;
			}
		?>
		
		<script type="text/javascript">
			var path="<?php echo $this->util()->getPath(); ?>";

			jQuery(document).ready(function () {
				jQuery.scriptPath = "<?php echo $this->util()->getPath(); ?>";
				jQuery.struts2_jquery.local = "es";
				jQuery.struts2_jquery.gridLocal = "es";
				jQuery.struts2_jquery.timeLocal = "en";
				jQuery.ajaxSettings.traditional = true;
				jQuery.ajaxSetup({
					cache: false
				});
			});
			
			$(document).ready(function(){
				$(document).ajaxStart(function(){
					$('#jqDialogCargando').dialog('open');
				});
				
				$(document).ajaxStop(function(){
					$('#jqDialogCargando').dialog('close');
				});
			});

			$(function(){
				$("input:submit, input:button, input:reset, button").button();
			});
		</script>
			
		<link rel="stylesheet" type="text/css" href="<?php echo $this->util()->getPath(); ?>js/lightbox/themes/default/jquery.lightbox.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->util()->getPath(); ?>js/lightbox/themes/default/jquery.lightbox2.css" />
		<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/lightbox/jquery.lightbox.js"></script>
		<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/lightbox/jquery.lightbox2.js"></script>
		<script type="text/javascript">$(document).ready(function(){$('.lightbox').lightbox();});</script>
		<script type="text/javascript">$(document).ready(function(){$('.lightbox2').lightbox2();});</script>
		
		<link href="<?php echo $this->util()->getPath();?>datatables/css/demo_page.css" rel="stylesheet" />
		<link href="<?php echo $this->util()->getPath();?>datatables/css/demo_table.css" rel="stylesheet" />
		<link href="<?php echo $this->util()->getPath();?>datatables/css/TableTools.css" rel="stylesheet" />
		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/jquery.dataTables.js"></script>
		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/ZeroClipboard.js"></script>
		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/TableTools.js"></script>
		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/FixedColumns.js"></script>
		
		<link href="<?php echo $this->util()->getPath();?>kendo/css/kendo.common.min.css" rel="stylesheet" />
	    <link href="<?php echo $this->util()->getPath();?>kendo/css/kendo.default.min.css" rel="stylesheet" />
	    <link href="<?php echo $this->util()->getPath();?>kendo/css/kendo.dataviz.min.css" rel="stylesheet" />
	    <link href="<?php echo $this->util()->getPath();?>kendo/css/kendo.bootstrap.min.css" rel="stylesheet" />
	    <link href="<?php echo $this->util()->getPath();?>kendo/css/examples.css" rel="stylesheet" />   
	    <script src="<?php echo $this->util()->getPath();?>kendo/js/kendo.all.js"></script> 
	    
	    <script src="<?php echo $this->util()->getPath();?>kendo/js/console.js"></script>
	    <script src="<?php echo $this->util()->getPath();?>kendo/js/prettify.js"></script>
	        
		<script src="<?php echo $this->util()->getPath();?>kendo/js/kendo.culture.es-PE.js"></script>
		<script>kendo.culture('es-PE');</script>	
		<script src="<?php echo $this->util()->getPath();?>kendo/js/kendo_fn.js"></script>
            
       		
		<link rel="stylesheet" type="text/css" href="<?php echo $this->util()->getPath();?>tree/css/ext-all.css" />
		<!--<link rel="stylesheet" type="text/css" href="<?php echo $this->util()->getPath();?>tree/css/examples.css" /> --> 
		<script type="text/javascript" src="<?php echo $this->util()->getPath();?>tree/js/yui-utilities.js"></script>
		<script type="text/javascript" src="<?php echo $this->util()->getPath();?>tree/js/ext-yui-adapter.js"></script>
		<script type="text/javascript" src="<?php echo $this->util()->getPath();?>tree/js/ext-all.js"></script>			    
	    <script type="text/javascript" src="<?php echo $this->util()->getPath();?>tree/js/AsyncTreeNode.js"></script>			
		<script type="text/javascript" src="<?php echo $this->util()->getPath();?>tree/js/TreeCheckNode.js"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->util()->getPath();?>tree/css/TreeCheckNode.css" />	 
       
       	
       
	</head>    
	<body>
	
		<?php 
			$ddatosuserlog = new Zend_Session_Namespace('datosuserlog');
			$coduser = $ddatosuserlog->cidpers;
	
			if($coduser == '' || $coduser == null){

				echo $this->layout()->content;
				
			}else{
				?>
					<table style="width: 100%; height: 100%; padding: 0px; margin: 0px;" cellspacing="0" cellpadding="0">
						<tr>
							<td style="background: url('<?php echo $this->util()->getImage("main-bg.gif"); ?>');" rowspan="4">&nbsp;</td>
							<td style="width: <?php echo $this->util()->getWidthLayout();?>; height: 42px; border-right: 1px solid #000; border-left: 1px solid #000;">
								<?php echo $this->render("northView.phtml"); ?>
							</td>
							<td style="background: url('<?php echo $this->util()->getImage("main-bg.gif"); ?>');" rowspan="4">&nbsp;</td>
						</tr>
						<tr>
							<td style="height: 30px; border-right: 1px solid #000; border-left: 1px solid #000;vertical-align: middle;">
								<?php echo $this->render("menuView.phtml"); ?>
							</td>
						</tr>
						<tr>
							<td style="height: 100%; border-right: 1px solid #000; border-left: 1px solid #000; vertical-align: top;">
								<div id="west" align="center">
									<?php echo $this->layout()->content; ?>
								</div>
							</td>
						</tr>
						<tr>
							<td id="south" class="ui-state-default" style="width: <?php echo $this->util()->getWidthLayout();?>; height: 30px;">
								<?php echo $this->render("southView.phtml"); ?>
							</td>
						</tr>
					</table>
				<?php
			}
		?>
	
		
		<?php echo $this->render("jqCargando.phtml"); ?>
		<?php echo $this->render("jqConfirm.phtml"); ?>
	</body>
</html>