<html>
	<head>
		<?php		
		echo $this->headMeta() . "\n";
		echo $this->headTitle() . "\n";
	
		?>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		
		<style type="text/css">
			.printable {
				border: 1px dotted #CCCCCC ;
				padding: 10px 10px 10px 10px ;
			}
		</style>
	
		
		<?php echo $this->util()->getStyle(); ?>
		<link href="<?php echo $this->util()->getPath(); ?>theme/blue_explora/jquery-ui.css" rel="stylesheet" type="text/css" id="jquery_theme_link" />
		<link href="<?php echo $this->util()->getImage("refbar.ico"); ?>" rel="shortcut icon" type="image/x-icon" />
		<link href="<?php echo $this->util()->getImage("refbar.ico"); ?>" rel="icon" type="image/x-icon" />
		<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCi3uGbWaukJjhm6WjuStB19XoIslLtvbk"></script>
		
		<!-- JQuery -->
	    <script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>/MDB/js/jquery-3.3.1.min.js"></script>
		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	    <!-- Bootstrap core CSS -->
	    <link href="<?php echo $this->util()->getPath(); ?>/MDB/css/bootstrap.min.css" rel="stylesheet">
	    <!-- Material Design Bootstrap -->
	    <link href="<?php echo $this->util()->getPath(); ?>/MDB/css/mdb.min.css" rel="stylesheet">
	    <!-- Your custom styles (optional) -->
	    <link href="<?php echo $this->util()->getPath(); ?>/MDB/css/style.css" rel="stylesheet">
		
		
		
		<?php
			//echo $this->util()->getScript("js/common");		
			
			$controller = $this->util()->getScriptJSController();
			$controllerAction = $this->util()->getScriptJSControllerAction();
			$leave = $this->util()->getScriptLeave();
			if(strlen($controller) > 0) {
				
				echo $controller;
			}
			
			if(strlen($controllerAction) > 0) {
				echo $controllerAction;
			}
			
			if(strlen($leave) > 0) {
				echo $leave;
			}
		?>
		
		<script type="text/javascript">
			var path="<?php echo $this->util()->getPath(); ?>";

//			jQuery(document).ready(function () {
//				jQuery.scriptPath = "<?php echo $this->util()->getPath(); ?>";
//				jQuery.struts2_jquery.local = "es";
//				jQuery.struts2_jquery.gridLocal = "es";
//				jQuery.struts2_jquery.timeLocal = "en";
//				jQuery.ajaxSettings.traditional = true;
//				jQuery.ajaxSetup({
//					cache: false
//				});
//			});			
//			$(document).ready(function(){
//				$(document).ajaxStart(function(){
//					$('#jqDialogCargando').dialog('open');
//				});
//				
//				$(document).ajaxStop(function(){
//					$('#jqDialogCargando').dialog('close');
//				});
//			});
//
//			$(function(){
//				$("input:submit, input:button, input:reset, button").button();
//			}); 
			
		</script>		
		<link href="<?php echo $this->util()->getPath();?>datatables/css/demo_page.css" rel="stylesheet" />
		<link href="<?php echo $this->util()->getPath();?>datatables/css/demo_table.css" rel="stylesheet" />
		<link href="<?php echo $this->util()->getPath();?>datatables/css/TableTools.css" rel="stylesheet" />
		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/jquery.dataTables.js"></script>
		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/ZeroClipboard.js"></script>
		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/TableTools.js"></script>
		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/FixedColumns.js"></script>
		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/FixedHeader.js"></script>
	        
	</head>    
	<body>
		<div class="w-screen">
			    
		    
		<?php 
			$ddatosuserlog = new Zend_Session_Namespace('datosuserlog');
			$codemp = $ddatosuserlog->codemp;
	
			if($codemp == '' || $codemp == null){
				
				echo $this->layout()->content;
				
			}else{
				?>					
					<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" style="padding: 0px; margin: 0px;">
					  <tr>
					    <td width="203px" rowspan="3" valign="top">
					    	<?php echo $this->render("menuView.phtml"); ?>
					    </td>
					    <td height="67" align="center" style="background: url('<?php echo $this->util()->getImage("footer_bg_cen.jpg"); ?>');">
					    	<?php echo $this->render("northView.phtml"); ?>
					    </td>					    
					  </tr>
					  <tr valign="middle" height="0px">
					    <td align="left" id="titulopag" style="font-weight: bold;font-size: 16px;">
					    	<!-- TITULO DE PAGINA -->
					    </td>
					  </tr>
					  <tr valign="top">
					    <td align="center" class="">
					    	<?php echo $this->layout()->content; ?>
					    </td>
					  </tr>
					  
					  <!-- 
					  <tr>
					    <td height="30px" colspan="2" style="background: url('<?php echo $this->util()->getImage("footer_bg_cen.jpg"); ?>');">
					    	<?php echo $this->render("southView.phtml"); ?>
					    </td>
					  </tr>
					   -->
					</table>
				<?php
			}
		?>
		</div>
		
	    <!-- Bootstrap tooltips -->
	    <script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>/MDB/js/popper.min.js"></script>
	    <!-- Bootstrap core JavaScript -->
	    <script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>/MDB/js/bootstrap.min.js"></script>
	    <!-- MDB core JavaScript -->
	    <script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>/MDB/js/mdb.js"></script>
		
		<?php //echo $this->render("jqCargando.phtml"); ?>
		<?php //echo $this->render("jqConfirm.phtml"); ?>
	</body>
</html>