<html>
	<head>
		<?php		
		echo $this->headMeta() . "\n";
		echo $this->headTitle() . "\n";
	
		?>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		
		<style type="text/css">
			.printable {
				border: 1px dotted #CCCCCC ;
				padding: 10px 10px 10px 10px ;
			}
		</style>
	
		
		<?php echo $this->util()->getStyle(); ?>
		<link href="<?php echo $this->util()->getPath(); ?>theme/blue_explora/jquery-ui.css" rel="stylesheet" type="text/css" id="jquery_theme_link" />
		<link href="<?php echo $this->util()->getImage("refbar.ico"); ?>" rel="shortcut icon" type="image/x-icon" />
		<link href="<?php echo $this->util()->getImage("refbar.ico"); ?>" rel="icon" type="image/x-icon" />
		<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCi3uGbWaukJjhm6WjuStB19XoIslLtvbk"></script>
		
		<!-- JQuery -->
	    <script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>MDB/js/jquery-3.3.1.min.js"></script>

		<link rel="stylesheet" href="<?php echo $this->util()->getPath(); ?>MDB/css/font-awesome.min.css">

	    <link href="<?php echo $this->util()->getPath(); ?>MDB/css/bootstrap.min.css" rel="stylesheet">
	    <link href="<?php echo $this->util()->getPath(); ?>/MDB/css/mdb.min.css" rel="stylesheet">
	    <link href="<?php echo $this->util()->getPath(); ?>MDB/css/style.css" rel="stylesheet">
		
		 <link href="<?php echo $this->util()->getPath(); ?>MDB/css/compiled.css" rel="stylesheet">
		
		<style>
		/*********************
  Pagination
**********************/
.pagination li {
  float: left;
  font-size: 1.2rem;
  line-height: 30px;
  border-radius: 2px;
  text-align: center;
}

.pagination li .active {
  background-color: #ee6e73;
}

.pagination li a {
  border: 0;
  color: #444;
}

.pagination li a:active {
  color: #000;
}

.pagination li a:hover {
  background-color: transparent;
}

.pagination-dark li {
  float: left;
  font-size: 1.2rem;
  line-height: 30px;
  border-radius: 2px;
  text-align: center;
}

.pagination-dark li .active {
  background-color: #ee6e73;
}

.pagination-dark li a {
  border: 0;
  color: #eee;
  background-color: transparent;
}

.pagination-dark li a:active {
  color: #000;
}

.pagination-dark li a:hover {
  background-color: transparent;
}

.pag-circle .active a {
  border-radius: 50%;
}
		
		</style>
		
		

		
		<script type="text/javascript">
			var path="<?php echo $this->util()->getPath(); ?>";
		</script>
				
<!--		<link href="<?php echo $this->util()->getPath();?>datatables/css/demo_page.css" rel="stylesheet" />-->
<!--		<link href="<?php echo $this->util()->getPath();?>datatables/css/demo_table.css" rel="stylesheet" />-->
<!--		<link href="<?php echo $this->util()->getPath();?>datatables/css/TableTools.css" rel="stylesheet" />-->
<!--		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/jquery.dataTables.js"></script>-->
<!--		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/ZeroClipboard.js"></script>-->
<!--		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/TableTools.js"></script>-->
<!--		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/FixedColumns.js"></script>-->
<!--		<script type="text/javascript" language="javascript" src="<?php echo $this->util()->getPath();?>datatables/js/FixedHeader.js"></script>-->
	        
	        
		    <link href="<?php echo $this->util()->getPath();?>datatables/css/TableTools.css" rel="stylesheet">
	        <link href="<?php echo $this->util()->getPath();?>datatables/css/dataTables.bootstrap.css" rel="stylesheet">   
		    <link href="<?php echo $this->util()->getPath();?>datatables/css/responsive.bootstrap.min.css" rel="stylesheet">
            <link href="<?php echo $this->util()->getPath();?>datatables/ext/responsive.bootstrap.min.css" rel="stylesheet">            
            <link href="<?php echo $this->util()->getPath();?>datatables/ext/buttons.bootstrap.css" rel="stylesheet">    
		<!--	        -->
	        
	    <link href='<?php echo $this->util()->getPath();?>fullcalendar-3.9.0/fullcalendar.min.css' rel='stylesheet' />
		<link href='<?php echo $this->util()->getPath();?>fullcalendar-3.9.0/fullcalendar.print.min.css' rel='stylesheet' media='print' />
		<script src='<?php echo $this->util()->getPath();?>fullcalendar-3.9.0/lib/moment.min.js'></script>
		<script src='<?php echo $this->util()->getPath();?>fullcalendar-3.9.0/lib/jquery.min.js'></script>
		<script src='<?php echo $this->util()->getPath();?>fullcalendar-3.9.0/fullcalendar.min.js'></script>
		<script src='<?php echo $this->util()->getPath();?>fullcalendar-3.9.0/locale-all.js'></script>    
		
				<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="<?php echo $this->util()->getPath();?>bootstrap-select-1.13.1/dist/css/bootstrap-select.min.css">
	        
	        
	    <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/js/jquery.dataTables.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/js/dataTables.bootstrap.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/js/ZeroClipboard.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/js/TableTools.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/js/FixedColumns.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/js/FixedHeader.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/js/dataTables.responsive.min.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/js/responsive.bootstrap.min.js"></script>
            
			<script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/js/dataTables.buttons.js"></script>
           
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/ext/jszip.min.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/ext/pdfmake.min.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/ext/vfs_fonts.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/ext/buttons.html5.min.js"></script>
               
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/ext/buttons.print.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/ext/buttons.colVis.js"></script>
            
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/ext/dataTables.responsive.min.js"></script>
            <script type="text/javascript"  src="<?php echo $this->util()->getPath();?>datatables/ext/responsive.bootstrap.min.js"></script>    
	        
	        
	        		<?php
			//echo $this->util()->getScript("js/common");		
			
			$controller = $this->util()->getScriptJSController();
			$controllerAction = $this->util()->getScriptJSControllerAction();
			$leave = $this->util()->getScriptLeave();
			if(strlen($controller) > 0) {
				
				echo $controller;
			}
			
			if(strlen($controllerAction) > 0) {
				echo $controllerAction;
			}
			
			if(strlen($leave) > 0) {
				echo $leave;
			}
		?>
	        
	    <script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/js_ws.js"></script>
		<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/js_ws_tools.js"></script>   
	       
	        
	</head>    
	<body class="">
		<div class="container-fluid">
			    
		    
		<?php 
			$ddatosuserlog = new Zend_Session_Namespace('datosuserlog');
			$codemp = $ddatosuserlog->codemp;
	
			if($codemp == '' || $codemp == null){
				
				echo $this->layout()->content;
				
			}else{
				?>	
						    <div class="row">
						        <div class="col-md-2 collapse in show" id="sidebar">
						            <div class="list-group panel" style="height: 100vh" >
						            
						            <?php echo $this->render("menuView.phtml"); ?>
						            
									<!--						             
						                <a href="#menu1" class="list-group-item collapsed" data-toggle="collapse" data-parent="#sidebar" aria-expanded="false"><i class="fa fa-dashboard"></i> <span class="hidden-sm-down">Item 1</span> </a>
						                <div class="collapse" id="menu1">
						                    <a href="#menu1sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false">Subitem 1 </a>
						                    <div class="collapse" id="menu1sub1">
						                        <a href="#" class="list-group-item" data-parent="#menu1sub1">Subitem 1 a</a>
						                        <a href="#" class="list-group-item" data-parent="#menu1sub1">Subitem 2 b</a>
						                        <a href="#menu1sub1sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false">Subitem 3 c </a>
						                        <div class="collapse" id="menu1sub1sub1">
						                            <a href="#" class="list-group-item" data-parent="#menu1sub1sub1">Subitem 3 c.1</a>
						                            <a href="#" class="list-group-item" data-parent="#menu1sub1sub1">Subitem 3 c.2</a>
						                        </div>
						                        <a href="#" class="list-group-item" data-parent="#menu1sub1">Subitem 4 d</a>
						                        <a href="#menu1sub1sub2" class="list-group-item" data-toggle="collapse"  aria-expanded="false">Subitem 5 e </a>
						                        <div class="collapse" id="menu1sub1sub2">
						                            <a href="#" class="list-group-item" data-parent="#menu1sub1sub2">Subitem 5 e.1</a>
						                            <a href="#" class="list-group-item" data-parent="#menu1sub1sub2">Subitem 5 e.2</a>
						                        </div>
						                    </div>
						                    <a href="#" class="list-group-item" data-parent="#menu1">Subitem 2</a>
						                    <a href="#" class="list-group-item" data-parent="#menu1">Subitem 3</a>
						                </div>
						                <a href="#" class="list-group-item collapsed" data-parent="#sidebar"><i class="fa fa-film"></i> <span class="hidden-sm-down">Item 2</span></a>
						                <a href="#menu3" class="list-group-item collapsed" data-toggle="collapse" data-parent="#sidebar" aria-expanded="false"><i class="fa fa-book"></i> <span class="hidden-sm-down">Item 3 </span></a>
						                <div class="collapse" id="menu3">
						                    <a href="#" class="list-group-item" data-parent="#menu3">3.1</a>
						                    <a href="#menu3sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false">3.2 </a>
						                    <div class="collapse" id="menu3sub2">
						                        <a href="#" class="list-group-item" data-parent="#menu3sub2">3.2 a</a>
						                        <a href="#" class="list-group-item" data-parent="#menu3sub2">3.2 b</a>
						                        <a href="#" class="list-group-item" data-parent="#menu3sub2">3.2 c</a>
						                    </div>
						                    <a href="#" class="list-group-item" data-parent="#menu3">3.3</a>
						                </div>
						                -->
						                
						            </div>
						        </div>
						        <main class="col-md-10">
<!--						            <a href="#sidebar" data-toggle="collapse"><i id="btn_menu" class="fa fa-navicon fa-lg"></i></a>-->
									
						            <hr>
<!--						            <div class="page-header">-->
<!--						                <h1>Bootstrap 4 Sidebar Menu</h1>-->
<!--						            </div>-->
						            <?php echo $this->layout()->content; ?>
						        </main>
						    </div>
				
					<!--		-----------------------------------						-->
					<?php //echo $this->render("menuView.phtml"); ?>
					    
				<?php
			}
		?>
		</div>
		
		
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.bundle.min.js"></script>		
<!--		<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>MDB/js/compiled.min.js"></script>-->
		<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>MDB/js/bootstrap.min.js"></script>
	    <script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>MDB/js/popper.min.js"></script>
	    <script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>MDB/js/mdb.js"></script>
				
		<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>bootstrap-select-1.13.1/dist/js/bootstrap-select.min.js"></script>
		
		
		<!-- Latest compiled and minified JavaScript -->
		
        <script>

//        var t = $($.fn.dataTable.tables(true)).dataTable(); 
//        if(t != null){
//                t.responsive.rebuild();
//                t.responsive.recalc();
//                t.columns.adjust();
//            }
        
        var boostrap_select = $('.selectpicker').selectpicker({
           style: 'btn-info',
           title: " "
        });
        //$('select:not(.selectpicker)').material_select();
        </script>
	</body>
</html>