<?php $url = $this->util()->getPath();
$ddatosuserlog = new Zend_Session_Namespace('datosuserlog');
$codemp = $ddatosuserlog->codemp;
$ns = 'pkg_appweb.sp_obt_menu';
$arraydatos[] = array(':p_cod_emp',$codemp);
$cn = new Model_DataAdapter();
$datos_menu = $cn->ejec_store_oracle_sisconv($ns,$arraydatos);
//echo $codemp;
?>
<div id="fondo" style="height: 100%">
<div style="height: 67px" align="center">
	<img src="<?php echo $this->util()->getImage("logo.png"); ?>" height="67px">
</div>	
	<nav id="menu-wrap">  				
			<?php  $this->util()->menu_buscar_hijos($datos_menu,'00000'); ?>
	</nav>
</div>