<?php 
	$url = $this->util()->getPath();
	$ddatosuserlog = new Zend_Session_Namespace('datosuserlog');
	$nompers = $ddatosuserlog->nombre . ' '. $ddatosuserlog->apepat . ' ' . $ddatosuserlog->apemat;
?>
<div>
	<div style="width: 67px;height: 67px;float:right;padding-left: 10px" align="center">
		<img src="<?php echo $this->util()->getImage("siluetaPersona.png"); ?>" height="67px">
	</div>
	<div style="width: 500px;float:right;">
		<div align="right" style="font-weight: bold;font-size: 16px">
		<?php echo $nompers;?>
		</div>		
		<div align="right" style="font-weight: bold;font-size: 12px">
		Area
		</div>
		<BR>
		<div align="right" style="font-weight: bold;font-size: 12px">
		(ROL)
		</div>
	</div>	
</div>

