<table>
	<tr>
		<td>DNI:</td>
		<td><input type="text" id="txtdni" value="" style="width: 200px " /></td>
	</tr>
	<tr>
		<td>Ape. Paterno:</td>
		<td><input type="text" id="txtpat" value="" style="width: 200px " /></td>
	</tr>
	<tr>
		<td>Ape. Materno:</td>
		<td><input type="text" id="txtmat" value="" style="width: 200px " /></td>
	</tr>
	<tr>
		<td>Nombres:</td>
		<td><input type="text" id="txtnom" value="" style="width: 200px " /></td>
	</tr>
	<tr><td colspan="2" align="center"><button id="btn_buscar">Buscar</button></td></tr>
</table>
<br>
<div id="div_buscar" style="width: 800px">
	
</div>
