<div style="background-color: #144f8f;height: 100%;width: 100%">
	<div class="cent" >
	    <div class="cent_tabl">
	      <div><img src="../../img/bg_caja_sup.png" width="440" height="60"/></div>
	
	      <div class="cont_logi">
	
	      <fieldset>
	
			  <div align="center" style="font-size: 18px;font-weight: bold">
	          	Reporte de Asistencia          
	          </div>
	          <br></br>
	          <div class="requisito">
	          <label class="label_logeo" style="width:140px;" for="txtdni">Doc. de Identidad<span class="span_logeo">Ingrese su DNI</span></label>
	          <input class="input_logeo" type="text" name="txtdni" id="txtdni"   maxlength="8" />
	          <!----><span class="span_logeo" id="usuario-mens" class="mens"></span>
	          </div>
	
	          <div class="requisito">
	          <label class="label_logeo" style="width:140px;"   for="txtanionac">A&ntilde;o de Nacimiento</label>
	          <input class="input_logeo" type="password" name="txtanionac" id="txtanionac" maxlength="4"/>
	          <!----><span class="span_logeo" id="password-mens" class="mens"></span>
	          </div>
	          
				<div align="center" style="font-size: 14px;font-weight: bold;color: red" id="div_msjerror"></div>
	          
	          <input type="button" class="ingr" id="btningreso" value="INGRESAR "/>	
	          	
	          
	        </fieldset>
	      </div>
	
	      <div><img src="../../img/bg_caja_inf.png" width="440" height="60"/></div>
	    </div>
	</div>
</div>