
<table border="0" cellpadding="0" cellspacing="0" width="100%" height="100%"><tr valign="top"><td align="center">

<div align="center"> 
	C&oacute;digo: <input type="text" id="txtcodpatrim" value="" maxlength="12"></input>
</div>
<br>

<div> <button id="btn_buscar">Buscar</button> </div>

<br>

<div  id="div_buscar">

</div>
<br>

<div id="div_roleo">
	Cantidad: <input type="text" id="txtcantidad" value="" maxlength="12"></input>

	<br>
	
	<button id="btn_rolear">Rolear</button> 
	
	<br>
	
	<div id="div_mensaje_roleo"></div>
	
</div>

</td></tr></table>