<div class="demo-section k-content"  style="width: 800px;font-weight: bold;font-size: 20px">
REPORTE DE ASISTENCIA POR PRACTICANTES
</div>
<div class="demo-section k-content"  style="width: 800px;">
	<table>
		<tr>
			<td width="70px">Empleados</td>
			<td width="10px"></td>
			<td></td>
		</tr>
		<tr>
			<td colspan="3">
			    <table cellpadding="0" cellspacing="0" border="1" id="tbl_empleados" width="800px">
			    
			    </table>		
			</td>
		</tr>
		<tr>
			<td>Fecha Inicio</td>
			<td>:</td>
			<td><input type="text" id="fecha_ini" value="" style="width: 100px" /></td>
		</tr>
		<tr>
			<td>Fecha Fin</td>
			<td>:</td>
			<td><input type="text" id="fecha_fin" value="" style="width: 100px" /></td>
		</tr>
		<tr>
			<td colspan="3" align="center">				
				<button id="btn_buscar">Generar Reporte</button>				
			</td>
		</tr>
	</table>
</div>


<div style="width: 100%" id="div_reporte">


</div>