<div align="center" style = "font-weight: bold">OPE</div>
<BR>
<form method="post" >
	<div align="center"> 
		DNI: <input type="text" id="txtdni" name="txtdni" value="" autofocus onchange="this.form.submit()"></input>
	</div>
	<div align="center">
		<input type="submit" id="btn_buscarx" value="Buscar">
	</div>
	<div id="div_buscar"></div>
</form>
<script>document.getElementById('txtdni').focus();</script>