<input type="hidden" id="txt_cod_emp" value="">
<div class="demo-section k-content"  style="width: 380px;font-weight: bold;font-size: 20px" id="txt_emp">
EMPLEADO xxx
</div>
<table cellpadding="0" cellspacing="0" border="1" id="tbl_marcacionesfueradehora">
			    
</table>
<br><br>
<b>Total de Horas Seleccionadas:   </b><span id="c_sumhorasextras" style="font-size: 20px">00:00</span> 
<br><br>
<b>Nro Papeleta:   </b> <input type="text" id="txt_nropapeleta" value="">
<br><br>
<div id="div_error_horasextrastomadas"></div>
<div align="center">
	<button id="btn_guardarhorasextrastomadas">Guardar</button> <button id="btn_cancelarhorasextrastomadas">Cancelar</button>
</div>





