
<div class="demo-section k-content"  style="width: 800px">
	<table>
		<tr>
			<td width="90px">Direc.Regional</td>
			<td width="30px">:</td>
			<td>
			    <select id="cbddrr" style="width: 400px"></select>			
			</td>
		</tr>
		<tr>
			<td>Dependencia</td>
			<td >:</td>
			<td>
			    <select id="cbdependencia" style="width: 400px"></select>			
			</td>
		</tr>
		<tr>
			<td>Unidad</td>
			<td >:</td>
			<td>
			    <select id="cbunidad" style="width: 400px"></select>			
			</td>
		</tr>
		<tr>
			<td>Empleado</td>
			<td>:</td>
			<td>
			    <select id="cbempleado" style="width: 400px"></select>			
			</td>
		</tr>
		<tr>
			<td>Fecha Inicio</td>
			<td>:</td>
			<td><input type="text" id="fecha_ini" value="" style="width: 100px" /></td>
		</tr>
		<tr>
			<td>Fecha Fin</td>
			<td>:</td>
			<td><input type="text" id="fecha_fin" value="" style="width: 100px" /></td>
		</tr>
		<tr>
			<td colspan="3" align="center">
				<button id="btn_buscar">Buscar</button>
				<br><br>
				<button id="btn_pdf_dirreg">Reporte por Dir. Regional</button>	
			</td>
		</tr>
	</table>
</div>


<div style="width: 100%" id="div_reporte">


</div>